version: '3'

networks:
  golangnet:
    driver: bridge

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../:/go/src
    ports:
      - "8080:8080"
    networks:
      - golangnet
    # environment: